spring:
  data:
    mongodb:
      database: UrlEntity
      host: localhost
      port: 27017
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/shortenUrl?serverTimezone=UTC&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
server:
  error:
    include-message: always